### ISSUE TITLE
th.conf

### ISSUE THREAD

**Issue by zwnk** [jervine/rpi-temp-humid-monitor#1]
Hi,
is it possible to get a template for the th.conf?
Somehow i guessed the syntax wrong. ;)

**Comment by jervine** [comment]
I've uploaded the /etc/th.conf file that I used. You'll need to replace the username with a MySQL user that can write to the database (and provide the password for that user too).

The config file code uses libconfig (from memory), so you'll need the dev package to compile the code, and you'll need the libconfig package to run the compiled code. I'm not really a C coder and my lack of knowledge here is what pushed me to start looking at the python option instead.

Hopefully this works for you!

**Comment by zwnk** [comment]
Thank you!
Yes i intalled libconfig-dev and was able to compile it. Thank you for the advice :+1:
