### ISSUE TITLE
error with SQL

### ISSUE THREAD

**Issue by speeskeek** [jervine/rpi-temp-humid-monitor#3]
root@minibian:~/new/rpi-temp-humid-monitor/c_code# ./th

File Type: Temperature and Humidity Monitoring Configuration File
th.c rev 1.9 04/06/2015 JDE Sat Aug 20 19:40:08 2016
Cycle time: 60 seconds, 3 retries
Sync to cycletime...
Current Temp:  23.5, Previous Temp:  50.0, Temperature Difference: -26.5C
Column count doesn't match value count at row 1
root@minibian:~/new/rpi-temp-humid-monitor/c_code# 

THe sql server is not local but on my NAS. planning to add more sensors, and let them all log into the same SQL (but other table). So later my NAS can render the web page.

But apparently my sql table is not good. can anyone halp?

**Comment by jervine** [comment]
Sorry, I haven't looked at this project in a _long_ time ... do you still have problems committing to a remote database? The error message looks like either more data was being passed than their were columns in the table (or less data than their were columns).

**Comment by speeskeek** [comment]
It is solved. Long time ago idee, dno how. But it works

Groeten,

Bart
