### ISSUE TITLE
Exception detected

### ISSUE THREAD

**Issue by arfbarky** [jervine/rpi-temp-humid-monitor#4]
I realize this code is fairly old, I've managed to cobble the system together so far between the Instructables article, this code repository and some trial and error. But I'm getting "Warning: Exception detected!" and it fails to retrieve sensor readings with the Python scripts. I have the right configuration in /etc/thMonitor.conf, correct sensor setting and RPI pin number. Any suggestions?

**Comment by jervine** [comment]
Does it work at all? Sometimes (after reading correctly) the sensor stops detecting the temperature and humidity, and a hard reset is the only thing that seems to clear it.
Is there any other output besides 'exception detected'?
Apologies for the delayed response.

**Comment by arfbarky** [comment]
I dunno, after messing with it for awhile longer, I gave up.
